CREATE SCHEMA BESTPRICE;

CREATE TABLE BESTPRICE.STORE(
	sId INT NOT NULL,
	Sname VARCHAR(50),
	Street VARCHAR(50),
	City VARCHAR(15),
	StateAb CHAR(2),
	ZipCode VARCHAR(15),
	Sdate DATE,
	Telno VARCHAR(12),
	URL VARCHAR(50),
	PRIMARY KEY (sId)
);

CREATE TABLE BESTPRICE.VENDOR (
	vId INT NOT NULL,
	PRIMARY KEY (vId), 
	Vname VARCHAR(50), 
	Street VARCHAR(50), 
	City VARCHAR(50), 
	StateAb CHAR(2), 
	Zipcode VARCHAR(11), 
	Vemail VARCHAR(50), 
	VTelNo VARCHAR(11)
);

CREATE TABLE BESTPRICE.VENDOR_STORE (
	vId INT NOT NULL, 
	sId INT NOT NULL,
	PRIMARY KEY(vId, sId),
	FOREIGN KEY (vId) REFERENCES VENDOR(vId),
	FOREIGN KEY (sId) REFERENCES STORE(sId)
);

CREATE TABLE BESTPRICE.CUSTOMER (
	cId INT NOT NULL,
	PRIMARY KEY (cId), 
	Cname VARCHAR(50), 
	Street VARCHAR(50), 
	City VARCHAR(50), 
	StateAb CHAR(2), 
	Zipcode VARCHAR(11), 
	CTelNo VARCHAR(11), 
	Cdob DATE
);

CREATE TABLE BESTPRICE.CONTRACT (
	vId INT NOT NULL, 
	ctId INT NOT NULL,
	PRIMARY KEY (vId, ctId),
	FOREIGN KEY (vId) REFERENCES VENDOR(vId), 
	Sdate DATE, 
	Ctime TIME, 
	Ctname VARCHAR(50)
);

CREATE TABLE BESTPRICE.ITEM (
	iId INT NOT NULL,
	PRIMARY KEY (iId), 
	Iname VARCHAR(50), 
	Sprice INT, 
	Idescription VARCHAR(150)
);

CREATE TABLE BESTPRICE.VENDOR_ITEM (
	vId INT NOT NULL, 
	iId INT NOT NULL,
	PRIMARY KEY (vId, iId),
	FOREIGN KEY (vId) REFERENCES VENDOR(vId),
	FOREIGN KEY (iId) REFERENCES ITEM(iId), 
	Vprice INT
);

CREATE TABLE BESTPRICE.ORDERS (
	oId INT NOT NULL, 
	sId INT NOT NULL,
	PRIMARY KEY (oId, sId),
	FOREIGN KEY (sId) REFERENCES STORE(sId),
	cId INT NOT NULL,
	FOREIGN KEY (cId) REFERENCES CUSTOMER(cId), 
	Odate DATE , 
	Ddate DATE , 
	Amount INT
);

CREATE TABLE BESTPRICE.ORDER_ITEM (
	oId INT NOT NULL, 
	sId INT NOT NULL, 
	iId INT NOT NULL,
	PRIMARY KEY (oId, sId, iId),
	FOREIGN KEY (oId) REFERENCES ORDERS(oId),
	FOREIGN KEY (sId) REFERENCES STORE(sId),
	FOREIGN KEY (iId) REFERENCES ITEM(iId),
	Icount INT
);

CREATE TABLE BESTPRICE.STORE_ITEM (
	sId INT NOT NULL, 
	iId INT NOT NULL,
	PRIMARY KEY(sId, iId),
	FOREIGN KEY (sId) REFERENCES STORE(sId),
	FOREIGN KEY (iId) REFERENCES ITEM(iId),
	Scount INT
);

CREATE TABLE BESTPRICE.STORE_CUSTOMER (
	sId INT NOT NULL, 
	cId INT NOT NULL,
	PRIMARY KEY(sId, cId),
	FOREIGN KEY (sId) REFERENCES STORE (sId),
	FOREIGN KEY (cId) REFERENCES CUSTOMER(cId)
);

CREATE TABLE BESTPRICE.EMPLOYEE (
	sId INT NOT NULL, 
	SSN INT NOT NULL,
	PRIMARY KEY (SSN),
	FOREIGN KEY (sId) REFERENCES STORE(sId),
	Ename VARCHAR(50),
	Street VARCHAR(50), 
	City VARCHAR(50), 
	StateAb CHAR(2), 
	Zipcode VARCHAR(11),
	Etype CHAR(1),
	Bdate DATE,
	Sdate DATE,
	Edate DATE, 
	eLevel VARCHAR(50), 
	Asalary INT(6), 
	Agency VARCHAR(50), 
	Hsalary INT, 
	Institute VARCHAR(50), 
	Itype CHAR(1), 
	TelNo VARCHAR(11), 
	Email VARCHAR(50)
);

CREATE TABLE BESTPRICE.FEEDBACK (
	cId INT NOT NULL,
	rId INT NOT NULL,
	PRIMARY KEY (cId, rId),
	FOREIGN KEY (cId) REFERENCES CUSTOMER(cId),
	Rating INT, 
	Comments VARCHAR(160)
);